from enum import StrEnum


class Source(StrEnum):
    RAZORPAY = "RAZORPAY"
    BANK = "BANK"
    LEDGER = "LEDGER"


class ExceptionType(StrEnum):
    BANK_FEE = "BANK_FEE"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    MISSING_BANK_RECEIPT = "MISSING_BANK_RECEIPT"
    DATE_DRIFT = "DATE_DRIFT"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    UNRESOLVABLE = "UNRESOLVABLE"


class ExceptionStatus(StrEnum):
    AUTO_SUGGESTED = "AUTO_SUGGESTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNRESOLVED = "UNRESOLVED"
    RESOLVED = "RESOLVED"


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    AI = "AI"
    HUMAN = "HUMAN"


MATCH_RULE = "order_ref+amount+24h"
WINDOW_HOURS = 24
LOW_CONFIDENCE_RETRY = 0.6
AUTO_SUGGEST_THRESHOLD = 0.85
MANUAL_MINUTES_PER_EXCEPTION_ASSUMED = 3
CURRENCY = "INR"
